### ISSUE TITLE
Create docs/steps for how to deploy blockchain on a container

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tf_jukebox#19]
we need to know the full steps of how to deploy a blockchain node to make it  up and running

**Comment by abdulgig** [comment]
@ashraffouda , as discussed the list of projects is here and we will pick first 4 to start off,

- [x] 1. Dash
- [x] 2. Digibyte
- [x] 3. Presearch

**Following is the workflow we follow to deploy a blockchain node on the market place.**

- [x] Get all requirements from the partner / official wikis
- [x]  Prepare docker images
- [x]  Prepare helm charts
- [x]  Prepare chat flows
- [x]  Prepare node status page
- [x]  Test and Roll out

Since the containers will run through the flists, the fastest way to deploy nodes would be to use existing docker images from the helm charts and convert them to flists.

As a starting point, we can use Presearch and Digibyte. I'll try to update with instructions for each of these separately somewhere.

**Comment by ashraffouda** [comment]
duplicate of https://github.com/threefoldtech/tf-images/issues/32
